version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_value:

services:
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: dansen95/yamdb_final
    restart: always
    volumes:
      - static_volume:/code/static/
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.0-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    ports:
      - 80:80
    depends_on:
      - web
    environment:
      - SERVER_NAME=localhost 84.252.129.10
        